config/routes.rb
Rails.application.routes.draw do
  resources :game, only: [:index, :show, :edit, :update, :new, :create]
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 20 }
  validates :se_volume, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :bgm_volume, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  mount_uploader :avatar, AvatarUploader

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'ゲスト') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception           # クロスサイトリクエストフォージェリ (CSRF)への対応策

  before_action :configure_permitted_parameters, if: :devise_controller?
  # devise_controllerを使うときしか処理しない

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :comment, :avatar])
  end
end

app/controllers/concerns/sign_in_check.rb
module SignInCheck
  def sign_in_check
    return if user_signed_in?

    flash[:notice] = I18n.t("errors.messages.please_login")
    redirect_to(new_user_session_path)
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :sign_in_check, only: [:update, :edit, :new, :create]

  include SignInCheck

  def index
    @users = User.all.order(hiscore: "DESC")
  end

  def show
    @user = User.find_by(id: params[:id])

    return if @user.present?

    flash[:notice] = I18n.t("errors.messages.returned_to_the_ranking_page_because_the_specified_user_did_not_exist")
    redirect_to(game_index_path)
  end

  def new; end

  def create
    score = params[:score].to_i

    if current_user.hiscore < score
      current_user.hiscore = score
      current_user.save
      flash[:notice] = I18n.t("activerecord.messages.hiscore_update")
    else
      flash[:notice] = I18n.t("activerecord.messages.not_updating_hiscore")
    end

    redirect_to(game_index_path)
  end

  def edit; end

  def update
    current_user.se_volume = params[:user][:se_volume]
    current_user.bgm_volume = params[:user][:bgm_volume]

    if current_user.save
      flash[:notice] = I18n.t("activerecord.messages.setup_save")
      redirect_to(root_path)
    else
      flash[:notice] = current_user.errors.full_messages.join('<br>')
      redirect_to(edit_game_path(current_user.id))
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @game_status = { hiscore: current_user.hiscore, se_volume: current_user.se_volume, bgm_volume: current_user.bgm_volume } if user_signed_in?
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def create
    super
    create_internal
  end

  def create_internal; end

  def ensure_normal_user
    redirect_to new_user_session_path, alert: I18n.t("errors.messages.password_cannot_be_reset", name: "ゲストユーザー") if params[:user][:email].casecmp('guest@example.com').zero?
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: [:update, :destroy]

  def update
    super
    update_internal
  end

  def destroy
    super
    destroy_internal
  end

  def update_internal; end

  def destroy_internal; end

  def ensure_normal_user
    redirect_to root_path, alert: I18n.t("errors.messages.cannot_be_updated_and_deleted", name: "ゲストユーザー") if resource.email == 'guest@example.com'
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: I18n.t("activerecord.messages.logged_in_as", name: "ゲストユーザー")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/game/edit.html.erb
<div class="user-edit-frame">
  <div class="user-edit">
    <h1>設定</h1>
    <%= form_with model: current_user, local: true, url: {controller: 'game', action: 'update' } do |form| %>
      <p>効果音の音量(0~10で設定)</p>
      <%= form.number_field :se_volume, max: 10, min: 0, required: true %>
      <p>GBMの音量(0~10で設定)</p>
      <%= form.number_field :bgm_volume, max: 10, min: 0, required: true %>
      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
    <div>
      <%= link_to "ホーム画面に移動", root_path %>
    </div>
  </div>
<div>

app/views/game/index.html.erb
<div class="ranking">
  <div>
    <%= link_to "ホーム画面に移動", root_path %>
  </div>
  <table class = "ranking-table">
    <tr>
      <th>順位</th>
      <th>アイコン</th>
      <th>名前</th>
      <th>ハイスコア</th>
    </tr>
    <% @users.each_with_index do |user, i| %>
        <% if user_signed_in? && current_user.id == user.id %>
          <tr class = "current-user-ranking">
        <% else %>
          <tr>
        <% end %>
        <td><%= i + 1 %></td>
        <td><%= image_tag user.avatar.url, class: "avatar" %></td>
        <td><%= link_to user.name, game_path(id: user.id) %></td>
        <td><%= sprintf("%09d", user.hiscore) %></td>
        </tr>
    <% end %>
  </table>
  <div>
    <%= link_to "トップへ移動", "#header" %>
  </div>
</div>

app/views/game/new.html.erb
<% if browser.platform.android? || browser.device.ipad? || browser.device.iphone? || browser.device.mobile? %>
  <body oncontextmenu="return false"></body>
  <div class="game-button">
    <h2 id= "touch-character-menu">メニュー</h2>
    <%= image_tag 'ターゲットのアイコン.png', id: "touch-character-shot" %>
    <%= image_tag '矢印ボタン左.png', id: "touch-character-left" %>
    <%= image_tag '矢印ボタン左.png', id: "touch-character-up" %>
    <%= image_tag '矢印ボタン左.png', id: "touch-character-right" %>
    <%= image_tag '矢印ボタン左.png', id: "touch-character-down" %>
  </div>
<% end %>
  <%= javascript_include_tag "engine/game_instance" %>
  <%= javascript_include_tag "engine/sound" %>
  <%= javascript_include_tag "engine/enemy" %>
  <%= javascript_include_tag "engine/boss" %>
  <%= javascript_include_tag "engine/enemy_shot" %>
  <%= javascript_include_tag "engine/stage" %>
  <%= javascript_include_tag "engine/menu" %>
  <%= javascript_include_tag "engine/character" %>
  <%= javascript_include_tag "engine/character_bullet" %>
  <%= javascript_include_tag "engine/effect" %>
  <%= javascript_include_tag "engine/screen_effect" %>
  <%= javascript_include_tag "engine/item" %>
  <%= javascript_include_tag "engine/out" %>
  <%= javascript_include_tag "engine/image_load" %>
  <%= javascript_include_tag "engine/draw" %>
  <%= javascript_include_tag "game" %>

app/views/game/show.html.erb
<div class="user-show-frame">
  <div class="user-show">
    <h2><%= @user.name %></h2>
    <%= image_tag @user.avatar.url %>
    <h2>ハイスコア</h2>
    <h3><%= sprintf("%09d", @user.hiscore) %></h3>
    <h2 class="user-show-comment-title">コメント</h2>
    <h3 class="user-show-comment"><%= @user.comment %></h3>
  </div>
  <div class="user-show-home-link">
    <div>
      <%= link_to "ランキング", game_index_path %>
    </div>
    <div>
      <%= link_to "ホーム画面に移動", root_path %>
    </div>
  </div>
<div>

app/views/home/index.html.erb
<div class = "top-page-frame">
  <div class = "top-page">
    <% unless user_signed_in? %>
      <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post %>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to "ゲームスタート", new_game_path(@game_status), data: {"turbolinks" => false} %>
    <% end %>
    <%= link_to "ランキング", game_index_path %>
    <%= link_to "遊び方", "#operation-explanation" %>
    <% if user_signed_in? %>
      <%= link_to "設定", edit_game_path(current_user.id) %>
    <% end %>
    <%= link_to "素材提供者様", "#material-provider" %>
  </div>
  <div id = "operation-explanation">
    <hr>
    <h1>遊び方</h1>
    <h2>ステータス説明</h2>
    <div class = "status-explanation">
      <%= image_tag 'プレイ画面.png', class: "status-explanation-img" %>
      <p><br>Point：<br>100ポイント集まるとライフが1増える<br><br>Power：<br>100ポイントごとに自機の攻撃パターンが変化する。<br>また、ポイントが多いほど攻撃力が上がる</p>
    </div>
    <hr>
    <h2>アイテム</h2>
    <div class = "item-explanation">
      <div>
        <%= image_tag '小アイテム.png', class: "small-item-img" %>
        <p>赤アイテム：Powerが増える<br>青アイテム：Pointが増える<br>緑アイテム：Scoreが増える</p>
      </div><!--
   --><div>
        <%= image_tag '大アイテム.png', class: "big-item-img" %>
        <p>大アイテム：通常アイテムより獲得量UP</p>
      </div>
    </div>
    <hr>
    <h2>操作方法</h2>
    <% if browser.platform.android? || browser.device.ipad? || browser.device.iphone? || browser.device.mobile? %>
      <%= image_tag 'モバイル操作方法.png', class: "operation-explanation-img" %>
      <p>プレイ時は画面を横表示に</p>
    <% else %>
      <%= image_tag 'PC操作方法.png', class: "operation-explanation-img" %>
    <% end %>
    <%= link_to "トップへ移動", "#header", class: "top-move" %>
    <div class ="operation-explanation-bottom"></div>
  </div>
  <div id = "material-provider">
    <hr>
    <h1>素材提供者様</h1>
      <div class = "material-provider-name"><%= link_to "『nakano sound』", "https://www.nakano-sound.com", target: :_blank, rel: "noopener noreferrer" %></div><!--
   --><div class = "material-provider-url"><%= link_to"https://www.nakano-sound.com", "https://www.nakano-sound.com", target: :_blank, rel: "noopener noreferrer" %></div>
      <div class = "material-provider-name"><%= link_to "『創作堂さくら紅葉』", "https://yukizakura.net/", target: :_blank, rel: "noopener noreferrer" %></div><!--
   --><div class = "material-provider-url"><%= link_to"https://yukizakura.net/", "https://yukizakura.net/", target: :_blank, rel: "noopener noreferrer" %></div>
      <div class = "material-provider-name"><%= link_to "『魔王魂』", "https://maou.audio/", target: :_blank, rel: "noopener noreferrer" %></div><!--
   --><div class = "material-provider-url"><%= link_to"https://maou.audio/", "https://maou.audio/", target: :_blank, rel: "noopener noreferrer" %></div>
      <div class = "material-provider-name"><%= link_to "『効果音ラボ』", "https://soundeffect-lab.info/", target: :_blank, rel: "noopener noreferrer" %></div><!--
   --><div class = "material-provider-url"><%= link_to"https://soundeffect-lab.info/", "https://soundeffect-lab.info/", target: :_blank, rel: "noopener noreferrer" %></div>
      <div class = "material-provider-name"><%= link_to "『フリー効果音素材 くらげ工匠』", "http://www.kurage-kosho.info/", target: :_blank, rel: "noopener noreferrer" %></div><!--
   --><div class = "material-provider-url"><%= link_to"http://www.kurage-kosho.info/", "http://www.kurage-kosho.info/", target: :_blank, rel: "noopener noreferrer" %></div>
      <div class = "material-provider-name"><%= link_to "『On-Jin ～音人～』", "https://on-jin.com/", target: :_blank, rel: "noopener noreferrer" %></div><!--
   --><div class = "material-provider-url"><%= link_to"https://on-jin.com/", "https://on-jin.com/", target: :_blank, rel: "noopener noreferrer" %></div>
      <div class = "material-provider-name"><%= link_to "『Presys net.』", "https://www.presys.jp/", target: :_blank, rel: "noopener noreferrer" %></div><!--
   --><div class = "material-provider-url"><%= link_to"https://www.presys.jp/", "https://www.presys.jp/", target: :_blank, rel: "noopener noreferrer" %></div>
    <%= link_to "トップへ移動", "#header", class: "top-move" %>
    <div class ="material-provider-bottom"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>ひま撃ち</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BIZ+UDGothic&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless current_page?(new_game_path) %>
      <%= render "shared/header" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div id="header">
  <h1><%= link_to "ひま撃ち",root_path %></h1>
  <div class="header-right">
    <% if user_signed_in? %>
      <%= link_to 'プロフィール変更', edit_user_registration_path %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'アカウント登録', new_user_registration_path %>
      <%= link_to 'ログイン', new_user_session_path %>
    <% end %>
  </div>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if flash[:notice] %>
  <p class = "notice"><%= flash[:notice].html_safe %></p>
<% end %>